# https://docs.ros.org/en/lunar/api/robot_localization/html/integrating_gps.html

ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        sensor_timeout: 0.1
        two_d_mode: true
        world_frame: "odom"
        
        odom0: /mavros/global_position/local
        odom0_config: [true,  true,  true,
                       false, false, false,
                       true,  true,  true,
                       false, false, false,
                       false, false, false]
        
        imu0: /mavros/imu/data
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      true,  true,  true,
                      false, false, false]
        
        use_control: false
        print_diagnostics: true
